// All the random content that powers the Emporium.
window.EMPORIUM_DATA = {
  facts: [
    "Octopuses have three hearts, and two of them stop beating when they swim.",
    "Bananas are berries, but strawberries are not.",
    "A day on Venus is longer than a year on Venus.",
    "Honey found in ancient Egyptian tombs was still edible.",
    "Wombat poop is cube-shaped.",
    "The Eiffel Tower can grow about 15 cm taller in summer as the iron expands.",
    "Sharks existed before trees did.",
    "A group of flamingos is called a 'flamboyance'.",
    "Scotland's national animal is the unicorn.",
    "There are more possible chess games than atoms in the observable universe.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "The inventor of the Pringles can was partly buried in one.",
    "Cows have best friends and get stressed when separated.",
    "A bolt of lightning is about five times hotter than the surface of the Sun.",
    "Oxford University is older than the Aztec Empire.",
    "Hot water can sometimes freeze faster than cold water (the Mpemba effect).",
    "The shortest war in history lasted about 38 minutes.",
    "Butterflies taste with their feet.",
    "An adult human skeleton has 206 bones; a baby has around 300.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    "A jiffy is an actual unit of time: 1/100th of a second in some contexts.",
    "Koalas have fingerprints almost indistinguishable from human ones.",
    "Some turtles can breathe through their butts.",
    "A shrimp's heart is in its head.",
    "There's a species of jellyfish that is biologically immortal.",
    "Peanuts are not nuts; they're legumes.",
    "Your stomach gets a new lining every few days so it doesn't digest itself.",
    "The first oranges weren't orange; they were green.",
    "A snail can sleep for three years.",
    "Pineapples take about two years to grow.",
    "The word 'nerd' was first used by Dr. Seuss.",
    "Rats laugh when tickled.",
    "The moon has moonquakes.",
    "Wild flamingos are pink because of the shrimp and algae they eat.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "A 'moment' was a medieval unit of time equal to 90 seconds.",
    "Hippo milk is not actually pink. That one is an internet myth.",
    "Crows can recognize and remember human faces.",
    "The heart of a blue whale is about the size of a small car.",
    "Venus is the only planet that spins clockwise.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Sloths can hold their breath longer than dolphins.",
    "The Great Wall of China is not visible from the Moon with the naked eye.",
    "Tardigrades can survive the vacuum of space.",
    "Apples float because they are about 25% air.",
    "Some cats are allergic to humans.",
    "The world's oldest known joke is a Sumerian fart joke from around 1900 BC.",
    "A cloud can weigh more than a million pounds.",
    "Penguins propose with pebbles.",
    "Saturn would float in a bathtub big enough to hold it.",
    "There's a town in Norway called Hell, and it freezes over every winter.",
    "Starfish have no brain and no blood.",
    "A cockroach can live for a week without its head.",
    "Dolphins give each other names.",
    "Bees can recognize human faces.",
    "Lobsters were once so cheap they were fed to prisoners.",
    "Astronauts grow up to 3% taller in space.",
    "The Hawaiian alphabet has only 13 letters.",
    "An ostrich's eye is bigger than its brain."
  ],

  fortunes: [
    "A surprising sandwich will change your afternoon.",
    "You will find something you lost, but not the thing you're looking for.",
    "Your next great idea will arrive in the shower. Keep a waterproof notepad.",
    "Someone is thinking of you. It's probably about the money you owe them.",
    "The stars say yes. The moon says 'maybe after lunch'.",
    "Adventure awaits. It is currently stuck in traffic.",
    "You are the main character. Please act accordingly.",
    "A pigeon will judge you this week. Rise above it.",
    "Good things come to those who refresh the page.",
    "Do not trust the last cookie in the jar.",
    "You will soon be rewarded for a kindness you forgot you did.",
    "Today is a great day to learn a pointless skill.",
    "The answer is 42. The question is still loading.",
    "Your houseplants believe in you.",
    "A small cat will teach you a large lesson.",
    "Help! I'm trapped in a fortune cookie website!",
    "You will write excellent code today. Probably. Mostly.",
    "An unexpected snack is in your near future.",
    "Wear socks that match your ambitions.",
    "The universe is random. You, however, are delightful."
  ],

  eightBall: [
    "It is certain.", "Without a doubt.", "You may rely on it.", "Yes, definitely.",
    "As I see it, yes.", "Most likely.", "Outlook good.", "Signs point to yes.",
    "Reply hazy, try again.", "Ask again later.", "Better not tell you now.",
    "Cannot predict now.", "Concentrate and ask again.",
    "Don't count on it.", "My reply is no.", "My sources say no.",
    "Outlook not so good.", "Very doubtful.",
    "Only if a duck is involved.", "Ask a cat."
  ],

  excuses: {
    who: ["my goldfish", "my neighbour's llama", "the Wi-Fi router", "my evil twin",
      "a rogue Roomba", "my grandma's parrot", "the moon", "a very confident squirrel",
      "my smart fridge", "an interdimensional raccoon", "my left sock", "the group chat"],
    did: ["ate", "accidentally sold", "hid", "emotionally bonded with", "launched into orbit",
      "knitted a sweater out of", "filed taxes on", "hypnotized", "unionized", "sat on",
      "mailed to Belgium", "turned into soup"],
    what: ["my car keys", "my homework", "the only door handle", "my shoes", "my calendar",
      "all the spoons", "my motivation", "my password", "the stairs", "my alarm clock",
      "my entire weekend", "the concept of Tuesday"]
  },

  names: {
    band: {
      a: ["Electric", "Velvet", "Screaming", "Cosmic", "Midnight", "Radioactive", "Sad", "Neon",
        "Feral", "Glitter", "Haunted", "Tiny", "Sonic", "Suspicious"],
      b: ["Toasters", "Llamas", "Mustard", "Pancakes", "Wizards", "Spoons", "Hamsters", "Vortex",
        "Accountants", "Pigeons", "Teeth", "Cardigans", "Lasagna", "Robots"]
    },
    pet: {
      a: ["Sir", "Lady", "Captain", "Professor", "Little", "Baron", "Duchess", "Mister", "Agent", "Doctor"],
      b: ["Wiggles", "Noodle", "Biscuit", "Pickles", "Fluffernutter", "Waffles", "Beans", "Snuggles",
        "Muffin", "Tater Tot", "Sprinkles", "Gnocchi", "Pudding", "Zoomies"]
    },
    wizard: {
      a: ["Gandor", "Merlox", "Zanthar", "Elbrin", "Quillifax", "Morgath", "Thistlewick",
        "Balthazar", "Ignatius", "Fizzwhistle", "Orvyn", "Grimsby"],
      b: ["the Grey", "the Soggy", "of the Seventh Sock", "the Mildly Powerful", "Stormbeard",
        "the Forgetful", "of Endless Snacks", "the Unbothered", "Moonbottom", "the Slightly Singed",
        "of the Wobbling Tower", "the Punctual"]
    }
  },

  words: [
    { word: "Petrichor", type: "noun", def: "The pleasant smell of earth after rain." },
    { word: "Defenestration", type: "noun", def: "The act of throwing someone or something out of a window." },
    { word: "Bumfuzzle", type: "verb", def: "To confuse or fluster." },
    { word: "Collywobbles", type: "noun", def: "Butterflies in the stomach; nervousness." },
    { word: "Gobbledygook", type: "noun", def: "Language that is meaningless or hard to understand." },
    { word: "Snollygoster", type: "noun", def: "A shrewd, unprincipled person." },
    { word: "Lollygag", type: "verb", def: "To spend time aimlessly; to dawdle." },
    { word: "Kerfuffle", type: "noun", def: "A commotion or fuss, especially caused by conflicting views." },
    { word: "Cattywampus", type: "adjective", def: "Askew; in disarray." },
    { word: "Sonder", type: "noun", def: "The realization that each passerby has a life as vivid as your own." },
    { word: "Flibbertigibbet", type: "noun", def: "A frivolous, flighty, or excessively talkative person." },
    { word: "Tittynope", type: "noun", def: "A small quantity of something left over." },
    { word: "Borborygmus", type: "noun", def: "The rumbling sound made by gas moving in the intestines." },
    { word: "Hullabaloo", type: "noun", def: "A commotion; a fuss." },
    { word: "Susurrus", type: "noun", def: "A whispering or rustling sound." },
    { word: "Widdershins", type: "adverb", def: "In a direction contrary to the sun's course; counterclockwise." },
    { word: "Gongoozler", type: "noun", def: "A person who enjoys watching boats on canals." },
    { word: "Crapulence", type: "noun", def: "Sickness caused by excessive eating or drinking." },
    { word: "Ultracrepidarian", type: "noun", def: "Someone who gives opinions on matters beyond their knowledge." },
    { word: "Quockerwodger", type: "noun", def: "A wooden puppet on strings; a politician controlled by someone else." },
    { word: "Mumpsimus", type: "noun", def: "Stubbornly sticking to a mistake even after it's pointed out." },
    { word: "Brouhaha", type: "noun", def: "A noisy and overexcited reaction or response." },
    { word: "Serendipity", type: "noun", def: "The occurrence of happy events by chance." },
    { word: "Absquatulate", type: "verb", def: "To leave abruptly." }
  ],

  emojis: ["🦄", "🍕", "🐙", "🚀", "🌈", "🍩", "🐸", "👾", "🦖", "🌮", "🎈", "🪐", "🦆", "🍉", "⭐", "🧀"]
};
